#!/bin/sh
function myfunc
{
    echo "シェルスクリプト名 $0"
    echo "関数の第1引数 $1"
    echo "関数の第2引数 $2"
    echo "関数の第3引数 $3"
    echo "関数の第4引数 $4"
}
myfunc       # 関数を引数無しで実行
myfunc a b c # 関数を引数付きで実行
echo "シェルスクリプト名 $0"
echo "シェルスクリプトの第1引数 $1"
echo "シェルスクリプトの第2引数 $2"
echo "シェルスクリプトの第3引数 $3"
