/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yukung' at '15/06/28 10:39' with Gradle 2.1
 *
 * @author yukung, @date 15/06/28 10:39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
