// Generated by CoffeeScript 1.9.1

/*
  複数行コメント。
  コンパイル時に消去されず、出力先にも残る。
 */
'this is string';
var a, arr, b, f, i, j, name, obj, obj2, ref, text;

"this is " + (2 + 3);

name = 'yukung';

'#{name}';

"my name is " + name;

text = "aaa\n" + 'bbb' + "\nccc";

text = "  aaa\n" + 'bbb' + "\nccc";


function func() {
  var i = 3;
  return i;
}
;

a = [1, 2, 3];

b = [1, 2, 3];

[1, 2, 3];

[0, 1, 2];

arr = [0, 1, 2, 3];

for (i = j = 0, ref = arr.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
  console.log(i);
}

arr = ['a', 'b', 'c', 'd', 'e'];

arr.slice(1, 4);

obj = {
  a: 1,
  b: 2,
  c: 3
};

obj2 = {
  a: 4,
  b: 5,
  c: {
    d: 7,
    e: 8
  }
};


/*
func({
  a: 1,
  b: 2
})
 */

func({
  a: 1,
  b: 2
});

a = 3;

b = 2;

obj = {
  a: a,
  b: b,
  c: 1
};

f = function() {
  this.a = 3;
  this.b = 2;
  return obj = {
    a: this.a,
    b: this.b,
    c: 1
  };
};
