// Generated by CoffeeScript 1.9.1
var a, b, c, d, ref;

console.log(true);

console.log(false);

console.log(true);

console.log(false);

console.log(true);

console.log(false);

1 === true;

1 === true;

1 !== true;

1 === 2 || 3 === 3;

2 === 2 && 4 !== 3;

a = typeof null !== "undefined" && null !== null ? null : true;

b = void 0 != null ? void 0 : true;

c = (ref = {}) != null ? ref : true;

d = typeof false !== "undefined" && false !== null ? false : {};
